modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="Thanks to Harry Talks for his amazing tutorials." #optional
authors="Harry" #optional

[[mods]] #mandatory
modId="mmpmod" #mandatory
version="0.1.0" #mandatory
displayName="MMP Mod" #mandatory
description='''
Mod for the MMP Server
'''

[[dependencies.mmpmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.mmpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"